// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/api/create-stryve-order": {
    params: {};
  };
  "/payments/callback": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/webhooks": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/app": {
    params: {};
  };
  "/app/payments": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/api/create-stryve-order" | "/payments/callback" | "/auth/login" | "/webhooks" | "/auth/*" | "/app" | "/app/payments";
  };
  "routes/api.create-stryve-order.jsx": {
    id: "routes/api.create-stryve-order";
    page: "/api/create-stryve-order";
  };
  "routes/payments.callback.jsx": {
    id: "routes/payments.callback";
    page: "/payments/callback";
  };
  "routes/auth.login/route.jsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/webhooks.jsx": {
    id: "routes/webhooks";
    page: "/webhooks";
  };
  "routes/_index/route.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/auth.$.jsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/app.jsx": {
    id: "routes/app";
    page: "/app" | "/app/payments";
  };
  "routes/app.payments.jsx": {
    id: "routes/app.payments";
    page: "/app/payments";
  };
  "routes/app._index.jsx": {
    id: "routes/app._index";
    page: "/app";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/api.create-stryve-order": typeof import("./app/routes/api.create-stryve-order.jsx");
  "routes/payments.callback": typeof import("./app/routes/payments.callback.jsx");
  "routes/auth.login": typeof import("./app/routes/auth.login/route.jsx");
  "routes/webhooks": typeof import("./app/routes/webhooks.jsx");
  "routes/_index": typeof import("./app/routes/_index/route.jsx");
  "routes/auth.$": typeof import("./app/routes/auth.$.jsx");
  "routes/app": typeof import("./app/routes/app.jsx");
  "routes/app.payments": typeof import("./app/routes/app.payments.jsx");
  "routes/app._index": typeof import("./app/routes/app._index.jsx");
};